name: Feature / Fix branch
on:
  push:
    branches:
      - 'feature/*'  # Fixed from 'feature**'
      - 'fix/*'      # Fixed from 'fix**'

jobs:
  python-ci:
    uses: ./.github/workflows/python-ci.yml
    secrets: inherit